### PR TITLE
#157735423 Build out the Login Page

### PR DESCRIPTION
**Pull request by joelmachango**
**What does this PR do?**
Have a responsive **log in** page built in HTML and CSS

**Description of task completed**?
1. Have a form for users to input username and password. 
2. Have a button for users to submit the username and password.
3. Style the login form
4. Add navigation to link login page with signup and requests
5. Style the top navigation
5. Add footer 
6. Add favicon
7. Have the login page responsive

**How should this be manually tested?**
`$ git clone https://github.com/joelmachango/maintenance-tracker.git`

- Navigate to the UI directory, Then click the login.html file to view the webpage on a browser

**Any background context you want to provide**
None

**What is the relevant pivotal tracker stories?**

> [#157735423](https://www.pivotaltracker.com/n/projects/2173255)

**Screenshots (if available)**

> Display on Mobile

day2_standup

> Display on a tablet

tablet-mode

> Display on a descktop

image

### CODE REVIEW

**Comment by johnmusiu** [comment]
Smooth design
Good PR structure.
Impressed with the commits history.

**Comment by DennisWanjiru** [comment]
The PR is well structured with lots of details and the design is pretty.

**Comment by lawrenceChege** [comment]
Well done, your commits are nice and precise.
your Pr is well structured.
good UI design.

**Comment by joelmachango** [comment]
well received. Thank you for the feedback @johnmusiu @DennisWanjiru @asamisellah @lawrenceChege

**Comment by joelmachango** [comment]
> Merge

 **Login page** branch to **develop** branch after review.

**Comment by RuthNjeri** [comment]
Looks great. The design is amazing and the structure of the PR and commit messages follow the guidelines.

**Pull request merged**
