### PR TITLE
#157735444 Built out the Create Requests UI template. 

### PR DESCRIPTION
**Pull request by joelmachango**
**What does this PR do?**
Have a modal that allows users to add a request, built in HTML, CSS and vanilla Javascript

**Description of task completed**?
1. Have a modal that is called once a user clicks the add request button.
2. Have an input field where users can add a request.
3. Have the modal close once a user clicks the close button.
4. Have the modal close once a user clicks anywhere on the modal.
5. Have the modal appearance and transformation appealing to a user.

**How should this be manually tested?**
`$ git clone https://github.com/joelmachango/maintenance-tracker.git`

`$ git checkout ft-user-requests-#157735444`

- Navigate to the UI directory. Open the requests.html on a browser and click *add request.*

**Any background context you want to provide**

> This page allows a user to make a request.

**What is the relevant pivotal tracker stories?**

> [#157735444](https://www.pivotaltracker.com/n/projects/2173255/stories/157735444)

**Screenshots (if available)**

image

**Questions**

> What improvements can I make?

### CODE REVIEW

**Comment by blac-siren** [comment]
Nice done. :+1:

**Comment by RuthNjeri** [comment]
looks good. Follows all the guidelines. Maybe you can add the input for a title and description of the request.

**Comment by joelmachango** [comment]
@RuthNjeri Noted. Thanks!

**Comment by antokish** [comment]
The PR is nice, Are we allowed to use vanilla js?

**Comment by joelmachango** [comment]
@antokish yap! What is not allowed is JQuery.

**Comment by antokish** [comment]
Thanks @joelmachango I didn't know...

**Comment by lawrenceChege** [comment]
it is great. follow what @RuthNjeri  said add more fields

**Comment by joelmachango** [comment]
@lawrenceChege Noted. Shukran!

**Comment by maxwellgithinji** [comment]
UI looks good, Dont forget to constanly refer to the requirements to be met in [Challenge 1] (https://docs.google.com/document/d/1_579P_foh3rYVSlXXOtrZTGVRAbQ16NmOK9ejPY6hcM/edit)

**Comment by artorious** [comment]
Hi, I really like it. Small screen devices view needs tweaking. have you tested on small screen? The reuests page specifically.

**Comment by Slinjez** [comment]
@maxwellgithinji the guidelines document.... very important

**Comment by joelmachango** [comment]
@maxwellgithinji  @artorious @Slinjez  Noted. I will look into the issues raised.

**Comment by asamisellah** [comment]
I would suggest making the form more discriptive by adding fields like title and description, for example

**Comment by DennisWanjiru** [comment]
Looks good.  But I suggest you add some more fields to the form

**Pull request merged**
