### PR TITLE
#157733930 Build out the SIgnup Page

### PR DESCRIPTION
**Pull request by joelmachango**
**What does this PR do?**
Have a responsive **Sign Up** page built in HTML and CSS

**Description of task completed**?
1. Have a form for users to input username and password. 
2. Have a button for users to submit the username and password.
3. Style the signup form to make it responsive

**How should this be manually tested?**
`$ git clone https://github.com/joelmachango/maintenance-tracker.git`

- Navigate to the UI directory, Then click the signup.html file to view the webpage on a browser

**Any background context you want to provide**
N/A

**What is the relevant pivotal tracker stories?**

> [#157733930](https://www.pivotaltracker.com/n/projects/2173255)

**Screenshots (If Any)**

image

### CODE REVIEW

**Comment by RuthNjeri** [comment]
Looks good. I think the link to requests should be visible only if the user has signed in.

**Comment by joelmachango** [comment]
@RuthNjeri Noted. I will rectify that

**Comment by lawrenceChege** [comment]
Commit are fine and precise.
the uI design is also great

**Comment by lawrenceChege** [comment]
also follow what @RuthNjeri said about requests.
In the description, include git checkout to branch so that one can see the updated files

**Comment by joelmachango** [comment]
Noted! Thank you. @lawrenceChege

**Comment by gitaumoses4** [comment]
This is great. I love the use of a dark theme. 
## Suggestions
- Reword this commit message `git commit -m "[Feature #157733930]Add media queries" ` to `[Feature #157733930] Add media queries`
- Rename the branch name to not include the hash(#)

**Pull request merged**
