### PR TITLE
#157735444 Build out an update to Create Requests UI template. 

### PR DESCRIPTION
**Pull request by joelmachango**
**What does this PR do?**
Have a modal that allows users to add a request, built in HTML, CSS and vanilla Javascript

**Description of task completed**?
1. Have a modal that is called once a user clicks the add request button.
2. Have a drop-down button where a user can select the type of request.
2. Have an input field where a user can add a request.
3. Have a submit button.

**How should this be manually tested?**
`$ git clone https://github.com/joelmachango/maintenance-tracker.git`

`$ git checkout ft-user-requests-modal-#157735444`

- Navigate to the UI directory. Open the requests.html on a browser and click *add request.*

**Any background context you want to provide**

> I took feedback from the previous [User-Request PR](https://github.com/joelmachango/maintenance-tracker/pull/4) and made improvements on the highlighted areas.

**What is the relevant pivotal tracker stories?**

> [#157735444](https://www.pivotaltracker.com/n/projects/2173255/stories/157735444)

**Screenshots (if available)**

request

request-dropdown

### CODE REVIEW

**Comment by lawrenceChege** [comment]
Nice work.. add request title though

**Comment by artorious** [comment]
Looks great. I love the pop-up dialogue box.

**Comment by asamisellah** [comment]
The desing is simple and clean

**Comment by joelmachango** [comment]
@artorious The page you're viewing is from an older branch.

`$ git checkout ft-user-requests-modal-#157735444`

to view the updated branch.

**Comment by joelmachango** [comment]
image

**Comment by blac-siren** [comment]
The PR is descriptive while the UI is great.
Nice work! :+1:

**Comment by alovega** [comment]
nice interface design and pT stories

**Comment by Melvin1Atieno** [comment]
I feel like the feel add request area is hanging since you've separated it from its title, you could try adding another title on the same area or attaching it to its title.

**Comment by joelmachango** [comment]
Noted @Melvin1Atieno

**Pull request merged**
