### PR TITLE
#157735703 Build out the admin dashboard

### PR DESCRIPTION
**Pull request by joelmachango**
**What does this PR do?**
Have an admin dashboard built in HTML and CSS.

**Description of task completed**?
1. Have an admin dashboard
2. Have a table consisting of all requests
3. Have an approve and reject button.
4. Have a search button.

**How should this be manually tested?**
`$ git clone https://github.com/joelmachango/maintenance-tracker.git`

`$ git checkout ft-user-requests-##157735703`

- Navigate to the UI directory. Open the *dashboard.html* file on a browser.

**Any background context you want to provide**

> This page allows the admin to view all requests

**What is the relevant pivotal tracker stories?**

> [#157735703](https://www.pivotaltracker.com/story/show/157735703)

> [#157735632](https://www.pivotaltracker.com/n/projects/2173255/stories/157735632)

> [#157735729](https://www.pivotaltracker.com/n/projects/2173255/stories/157735729)

**Screenshots (if available)**

image

**Questions**

> What improvements can I make?

### CODE REVIEW

**Comment by DennisWanjiru** [comment]
The PR is well docummented and Commits are atomic and follow convention. I suggest you add spacing between the green and red buttons

**Comment by joelmachango** [comment]
@DennisWanjiru Noted. Thanks!

**Comment by gitaumoses4** [comment]
Well laid and descriptive PR. Commits are concise and consistent.

I would suggest, you copy the PT story id directly from Pivotal Tracker. There's a :link:  icon on the left of the ID on each story.

**Comment by joelmachango** [comment]
@gitaumoses4 Noted. The link is broken. Let me remedy that.

**Comment by PaulKitonyi** [comment]
Wow great and descriptive PR.Can you help me out on how to have the feedback requested label on my PR.

**Comment by Slinjez** [comment]
Nice pr man, Maybe for the action buttons, you could do a dropdown...

**Comment by joelmachango** [comment]
@Slinjez Good idea

**Comment by joelmachango** [comment]
@PaulKitonyi  On the right side of this page there's a link named **labels** Click on it to create a custom label for your PR

**Comment by PaulKitonyi** [comment]
Ooh thanks for enlightening.

**Comment by joelmachango** [comment]
image

> Buttons resized 😉

**Comment by Slinjez** [comment]
@joelmachango that also looks good

**Comment by asamisellah** [comment]
Your PR is well written, the buttons look much better after the change. Maybe you could consider aligning the accept and reject buttons side by side horizontally.

**Pull request closed without merging**
