### PR TITLE
#157735749 Build out the dashboard where admin can give feedback to users.

### PR DESCRIPTION
**Pull request by joelmachango**
**What does this PR do?**
Have an admin dashboard built in HTML and CSS.

**Description of task completed**?
1. Have a dashboard where admin can give feedback for requests received.
2. Have a feedback form with fields to input a heading and a message.
3. Have a submit button.

**How should this be manually tested?**
`$ git clone https://github.com/joelmachango/maintenance-tracker.git`

`$ git checkout ft-admin-feedback-#157735749`

- Navigate to the UI directory. Open the *feedback.html* file on a browser.

**Any background context you want to provide**

> This page allows the admin to give feedback to users

**What is the relevant pivotal tracker stories?**

> [##157735749](https://www.pivotaltracker.com/n/projects/2173255/stories/157735749)

**Screenshots (if available)**

image

### CODE REVIEW

**Comment by artorious** [comment]
Your feedback format (like email) is great.

**Comment by joelmachango** [comment]
Well received! Thanks @lawrenceChege @artorious

**Comment by dalaineme** [comment]
Maybe consider having the search bar width the same as the elements below. Then the right nav connecting to the top one.

**Comment by maxwellgithinji** [comment]
Awesome UI, This is good.

**Pull request merged**
